import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Header from '@/components/Header';
import Image from 'next/image';
import pic from '@/public/img/pic.jpg';
import { useEffect } from 'react';
import firebase from '@/libs/firebase';


import { useGlobalData } from '@/hooks/useGlobalContext';


export default function Home() {
	
	const { LoginInfo ,setLoginInfo } = useGlobalData();
	// console.log(firebase)
	// fb
    useEffect(() => {
		console.log('LoginInfo?', LoginInfo)
		firebase.auth().onAuthStateChanged((userInfo) => {
			console.log('userinfo', userInfo);
			if (userInfo === null) setLoginInfo({ displayName: "", uid: "" });
			else setLoginInfo(userInfo.multiFactor.user);
		});
	}, [setLoginInfo]);


	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Header />


				<button
					onClick={() => {
						firebase.auth().signOut();
						alert('로그아웃 되었습니다.');
					}}
				>
					{' '}
					로그아웃
				</button>


				<h1>Main</h1>
				<div className={styles.pic}>
					<Image src={pic} alt='pic' fill quality={50} placeholder='blur' />
				</div>
				<div className={styles.pic}>
					<Image
						src='https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80'
						alt='pic'
						fill
						quality={50}
					/>
				</div>
			</main>
		</>
	);
}
